########################################################################
# Modify these variables to fit your system.
########################################################################

##################### Installation base directory
# This should point to /usr/local, for most people, or 
# to /usr if you want to integrate LCDproc into your main filesystem.
INSTALL_DIR = /usr/local

##################### Serial device
# This should be whatever your display is connected to.
# "make install" will create a link from /dev/lcd to DEVICE
# if you don't already have a /dev/lcd
DEVICE = /dev/ttyS0

##################### Operating System
# Uncomment the section for your OS.

### For Linux...
OS=-DLINUX

### For BSD. We call it xBSD to
# avoid a clash with the BSD in sys/param.h
#OS=-DxBSD

### For IRIX...
#OS=-DIRIX

### For Alpha processors...
#CFLAGS += -mieee

##################### Inet port to use...
# Use whatever you want...
# The default is 13666
LCDPORT=-DLCDPORT=13666

##################### Modescreen Options

##### Load Screen
# Max:  Load Avg at which the backlight will start blinking
MISC += -DLOAD_MAX=1.3
# Min:  Load Avg at which the backlight will turn off (asleep) 
MISC += -DLOAD_MIN=0.05

##### Filesystems to display stats for... (comment out ones you don't want)
# NFS (Network File System)
MISC += -DSTAT_NFS
# SMBFS (Samba filesystem -- Windows drives)
MISC += -DSTAT_SMBFS


##################### Drivers
# Comment out each section you don't want.

# Matrix-Orbital displays
DRIVERS += -DMTXORB_DRV
DOBJ += MtxOrb.o

# Wirz SLI
DRIVERS += -DSLI_DRV
DOBJ += wirz-sli.o

# CrystalFontz displays
DRIVERS += -DCFONTZ_DRV
DOBJ += CFontz.o

# Curses text-based output
DRIVERS += -DCURSES_DRV
DOBJ += curses_drv.o
LIB += -lncurses

# Regular text output (ugly)
DRIVERS += -DTEXT_DRV
DOBJ += text.o

# HD44780 parallel port lcd displays
#DRIVERS += -DHD44780_DRV
#DOBJ += hd44780.o
# Pick one of the following ports to use
#LPTPORT = 0x378
#LPTPORT = 0x278
#LPTPORT = 0x3bc

# Joystick input...  handy!
DRIVERS += -DJOY_DRV
DOBJ += joy.o

# Irman input...  handy!
#DRIVERS += -DIRMANIN_DRV
#DOBJ += irmanin.o ../../../libirman-0.4.1b/libirman.a
#IRMAN=1


##################### Debugging Options
# Please uncomment only one of these two, and comment the other:
# Uncomment this to build a debugging executable
#DEBUG = -g -DDEBUG
# If the above is commented, this shouldn't be...
MISC += -Wno-unused


########################################################################
# You shouldn't need to touch anything below here.
########################################################################

GCC = gcc -Wall -Wp,-lang-c-c++-comments -O6 $(CFLAGS)
VERSION = 0.4-pre9
MISC += $(OS) $(DRIVERS) $(DEBUG) $(LCDPORT) -DVERSION=\"$(VERSION)\"


###################################################################
# Compilation...
#
#all:
#	@echo Compiling LCDproc...
#	@for i in $(DIRS); do \
#		(cd $$i; [ -f Makefile ] && $(MAKE) $@) \
#	done; true

##################################################################
# Other stuff...
#
#clean:
#	@for i in $(DIRS); do \
#		(cd $$i; [ -f Makefile ] && $(MAKE) $@) \
#	done
#	rm -f *~ core
#
#edit:
#	emacs . &

#.PHONY : todo
#todo :
#	@echo ---------------===========================================
#	@grep -n TODO\\\|FIXME `find . -type f` | grep -v grep
#	@echo ---------------===========================================
