/** \file server/drivers/t6963_font.h
 * Font definition for use the t6963 driver.
 */

/*-
 * Copyright (c) 2001 Manuel Stahl <mythos@xmythos.de>
 *               2011 Markus Dolze <bsdfan@nurfuerspam.de>
 *
 * Parts of this file are based on the kernel driver by
 * Alexander Frink <Alexander.Frink@Uni-Mainz.DE>
 *
 * This file is released under the GNU General Public License. Refer to the
 * COPYING file distributed with this package.
 */

#define b______ 0x00
#define b_____O 0x01
#define b____O_ 0x02
#define b____OO 0x03
#define b___O__ 0x04
#define b___O_O 0x05
#define b___OO_ 0x06
#define b___OOO 0x07
#define b__O___ 0x08
#define b__O__O 0x09
#define b__O_O_ 0x0a
#define b__O_OO 0x0b
#define b__OO__ 0x0c
#define b__OO_O 0x0d
#define b__OOO_ 0x0e
#define b__OOOO 0x0f
#define b_O____ 0x10
#define b_O___O 0x11
#define b_O__O_ 0x12
#define b_O__OO 0x13
#define b_O_O__ 0x14
#define b_O_O_O 0x15
#define b_O_OO_ 0x16
#define b_O_OOO 0x17
#define b_OO___ 0x18
#define b_OO__O 0x19
#define b_OO_O_ 0x1a
#define b_OO_OO 0x1b
#define b_OOO__ 0x1c
#define b_OOO_O 0x1d
#define b_OOOO_ 0x1e
#define b_OOOOO 0x1f
#define b_OOOOO 0x1f
#define bO_____ 0x20
#define bO____O 0x21
#define bO___O_ 0x22
#define bO___OO 0x23
#define bO__O__ 0x24
#define bO__O_O 0x25
#define bO__OO_ 0x26
#define bO__OOO 0x27
#define bO_O___ 0x28
#define bO_O__O 0x29
#define bO_O_O_ 0x2a
#define bO_O_OO 0x2b
#define bO_OO__ 0x2c
#define bO_OO_O 0x2d
#define bO_OOO_ 0x2e
#define bO_OOOO 0x2f
#define bOO____ 0x30
#define bOO___O 0x31
#define bOO__O_ 0x32
#define bOO__OO 0x33
#define bOO_O__ 0x34
#define bOO_O_O 0x35
#define bOO_OO_ 0x36
#define bOO_OOO 0x37
#define bOOO___ 0x38
#define bOOO__O 0x39
#define bOOO_O_ 0x3a
#define bOOO_OO 0x3b
#define bOOOO__ 0x3c
#define bOOOO_O 0x3d
#define bOOOOO_ 0x3e
#define bOOOOOO 0x3f
#define bOOOOOO 0x3f

/**
 * Definition of a 6x8 font recreating the characters from CP437 with the
 * following exceptions at position:
 * \li 4 contains the open heart icon
 * \li 212-219 are vor vBars (bottom to top)
 * \li 220-224 are for hBars (growing right)
 * \li 247-251 are for hBars (growing left)
 * \li 228,246,252 contain small german umlaute (upper case are missing)
 * \li 243,244 contain ??
 */
unsigned char fontdata_6x8[256][8] = {
    [0x00] {b______,
	    b______,
	    b______,
	    b______,
	    b______,
	    b______,
	    b______,
	    b______},
    [0x01] {b__OOO_,
	    b_O___O,
	    b_OO_OO,
	    b_O___O,
	    b_O_O_O,
	    b_O___O,
	    b__OOO_,
	    b______},
    [0x02] {b__OOO_,
	    b_OOOOO,
	    b_O_O_O,
	    b_OOOOO,
	    b_O___O,
	    b_OOOOO,
	    b__OOO_,
	    b______},
    [0x03] {b______,
	    b__O_O_,
	    b_OOOOO,
	    b_OOOOO,
	    b_OOOOO,
	    b__OOO_,
	    b___O__,
	    b______},
    [0x04] {b______,
	    b______,
	    b__O_O_,
	    b__OOO_,
	    b__OOO_,
	    b___O__,
	    b______,
	    b______},
    [0x05] {b___O__,
	    b__OOO_,
	    b__OOO_,
	    b___O__,
	    b_OOOOO,
	    b_OOOOO,
	    b___O__,
	    b______},
    [0x06] {b______,
	    b___O__,
	    b__OOO_,
	    b_OOOOO,
	    b_OOOOO,
	    b___O__,
	    b__OOO_,
	    b______},
    [0x07] {b______,
	    b______,
	    b______,
	    b__OO__,
	    b__OO__,
	    b______,
	    b______,
	    b______},
    [0x08] {bOOOOOO,
	    bOOOOOO,
	    bOOOOOO,
	    bOO__OO,
	    bOO__OO,
	    bOOOOOO,
	    bOOOOOO,
	    bOOOOOO},
    [0x09] {b______,
	    b______,
	    b_OOOO_,
	    b_O__O_,
	    b_O__O_,
	    b_OOOO_,
	    b______,
	    b______},
    [0x0a] {bOOOOOO,
	    bOOOOOO,
	    bO____O,
	    bO_OO_O,
	    bO_OO_O,
	    bO____O,
	    bOOOOOO,
	    bOOOOOO},
    [0x0b] {b______,
	    b___OOO,
	    b____OO,
	    b__OO_O,
	    b_O__O_,
	    b_O__O_,
	    b__OO__,
	    b______},
    [0x0c] {b__OOO_,
	    b_O___O,
	    b_O___O,
	    b__OOO_,
	    b___O__,
	    b__OOO_,
	    b___O__,
	    b______},
    [0x0d] {b___O__,
	    b___OO_,
	    b___O_O,
	    b___O__,
	    b__OO__,
	    b_OOO__,
	    b_OO___,
	    b______},
    [0x0e] {b____OO,
	    b__OO_O,
	    b__O_OO,
	    b__OO_O,
	    b__O_OO,
	    b_OO_OO,
	    b_OO___,
	    b______},
    [0x0f] {b______,
	    b_O_O_O,
	    b__OOO_,
	    b_OO_OO,
	    b__OOO_,
	    b_O_O_O,
	    b______,
	    b______},
    [0x10] {b__O___,
	    b__OO__,
	    b__OOO_,
	    b__OOOO,
	    b__OOO_,
	    b__OO__,
	    b__O___,
	    b______},
    [0x11] {b____O_,
	    b___OO_,
	    b__OOO_,
	    b_OOOO_,
	    b__OOO_,
	    b___OO_,
	    b____O_,
	    b______},
    [0x12] {b___O__,
	    b__OOO_,
	    b_OOOOO,
	    b___O__,
	    b_OOOOO,
	    b__OOO_,
	    b___O__,
	    b______},
    [0x13] {b__O_O_,
	    b__O_O_,
	    b__O_O_,
	    b__O_O_,
	    b__O_O_,
	    b______,
	    b__O_O_,
	    b______},
    [0x14] {b__OOOO,
	    b_O_O_O,
	    b_O_O_O,
	    b__OO_O,
	    b___O_O,
	    b___O_O,
	    b___O_O,
	    b______},
    [0x15] {b__OOO_,
	    b_O___O,
	    b__OO__,
	    b__O_O_,
	    b___OO_,
	    b_O___O,
	    b__OOO_,
	    b______},
    [0x16] {b______,
	    b______,
	    b______,
	    b______,
	    b______,
	    b_OOOO_,
	    b_OOOO_,
	    b______},
    [0x17] {b___O__,
	    b__OOO_,
	    b_OOOOO,
	    b___O__,
	    b_OOOOO,
	    b__OOO_,
	    b___O__,
	    b__OOO_},
    [0x18] {b___O__,
	    b__OOO_,
	    b_OOOOO,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b______},
    [0x19] {b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b_OOOOO,
	    b__OOO_,
	    b___O__,
	    b______},
    [0x1a] {b______,
	    b___O__,
	    b___OO_,
	    b_OOOOO,
	    b___OO_,
	    b___O__,
	    b______,
	    b______},
    [0x1b] {b______,
	    b___O__,
	    b__OO__,
	    b_OOOOO,
	    b__OO__,
	    b___O__,
	    b______,
	    b______},
    [0x1c] {b______,
	    b______,
	    b______,
	    b_O____,
	    b_O____,
	    b_O____,
	    b_OOOOO,
	    b______},
    [0x1d] {b______,
	    b__O_O_,
	    b__O_O_,
	    b_OOOOO,
	    b__O_O_,
	    b__O_O_,
	    b______,
	    b______},
    [0x1e] {b___O__,
	    b___O__,
	    b__OOO_,
	    b__OOO_,
	    b_OOOOO,
	    b_OOOOO,
	    b______,
	    b______},
    [0x1f] {b_OOOOO,
	    b_OOOOO,
	    b__OOO_,
	    b__OOO_,
	    b___O__,
	    b___O__,
	    b______,
	    b______},
    [0x20] {b______,
	    b______,
	    b______,
	    b______,
	    b______,
	    b______,
	    b______,
	    b______},
    [0x21] {b___O__,
	    b__OOO_,
	    b__OOO_,
	    b___O__,
	    b___O__,
	    b______,
	    b___O__,
	    b______},
    [0x22] {b_OO_OO,
	    b_OO_OO,
	    b_O__O_,
	    b______,
	    b______,
	    b______,
	    b______,
	    b______},
    [0x23] {b______,
	    b__O_O_,
	    b_OOOOO,
	    b__O_O_,
	    b__O_O_,
	    b_OOOOO,
	    b__O_O_,
	    b______},
    [0x24] {b__O___,
	    b__OOO_,
	    b_O____,
	    b__OO__,
	    b____O_,
	    b_OOO__,
	    b___O__,
	    b______},
    [0x25] {b_OO__O,
	    b_OO__O,
	    b____O_,
	    b___O__,
	    b__O___,
	    b_O__OO,
	    b_O__OO,
	    b______},
    [0x26] {b__O___,
	    b_O_O__,
	    b_O_O__,
	    b__O___,
	    b_O_O_O,
	    b_O__O_,
	    b__OO_O,
	    b______},
    [0x27] {b__OO__,
	    b__OO__,
	    b__O___,
	    b______,
	    b______,
	    b______,
	    b______,
	    b______},
    [0x28] {b___O__,
	    b__O___,
	    b__O___,
	    b__O___,
	    b__O___,
	    b__O___,
	    b___O__,
	    b______},
    [0x29] {b__O___,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b__O___,
	    b______},
    [0x2a] {b______,
	    b__O_O_,
	    b__OOO_,
	    b_OOOOO,
	    b__OOO_,
	    b__O_O_,
	    b______,
	    b______},
    [0x2b] {b______,
	    b___O__,
	    b___O__,
	    b_OOOOO,
	    b___O__,
	    b___O__,
	    b______,
	    b______},
    [0x2c] {b______,
	    b______,
	    b______,
	    b______,
	    b______,
	    b__OO__,
	    b__OO__,
	    b__O___},
    [0x2d] {b______,
	    b______,
	    b______,
	    b_OOOOO,
	    b______,
	    b______,
	    b______,
	    b______},
    [0x2e] {b______,
	    b______,
	    b______,
	    b______,
	    b______,
	    b__OO__,
	    b__OO__,
	    b______},
    [0x2f] {b______,
	    b_____O,
	    b____O_,
	    b___O__,
	    b__O___,
	    b_O____,
	    b______,
	    b______},
    [0x30] {b__OOO_,
	    b_O___O,
	    b_O__OO,
	    b_O_O_O,
	    b_OO__O,
	    b_O___O,
	    b__OOO_,
	    b______},
    [0x31] {b___O__,
	    b__OO__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b__OOO_,
	    b______},
    [0x32] {b__OOO_,
	    b_O___O,
	    b_____O,
	    b___OO_,
	    b__O___,
	    b_O____,
	    b_OOOOO,
	    b______},
    [0x33] {b__OOO_,
	    b_O___O,
	    b_____O,
	    b__OOO_,
	    b_____O,
	    b_O___O,
	    b__OOO_,
	    b______},
    [0x34] {b____O_,
	    b___OO_,
	    b__O_O_,
	    b_O__O_,
	    b_OOOOO,
	    b____O_,
	    b____O_,
	    b______},
    [0x35] {b_OOOOO,
	    b_O____,
	    b_O____,
	    b_OOOO_,
	    b_____O,
	    b_O___O,
	    b__OOO_,
	    b______},
    [0x36] {b___OO_,
	    b__O___,
	    b_O____,
	    b_OOOO_,
	    b_O___O,
	    b_O___O,
	    b__OOO_,
	    b______},
    [0x37] {b_OOOOO,
	    b_____O,
	    b____O_,
	    b___O__,
	    b__O___,
	    b__O___,
	    b__O___,
	    b______},
    [0x38] {b__OOO_,
	    b_O___O,
	    b_O___O,
	    b__OOO_,
	    b_O___O,
	    b_O___O,
	    b__OOO_,
	    b______},
    [0x39] {b__OOO_,
	    b_O___O,
	    b_O___O,
	    b__OOOO,
	    b_____O,
	    b____O_,
	    b__OO__,
	    b______},
    [0x3a] {b______,
	    b______,
	    b__OO__,
	    b__OO__,
	    b______,
	    b__OO__,
	    b__OO__,
	    b______},
    [0x3b] {b______,
	    b______,
	    b__OO__,
	    b__OO__,
	    b______,
	    b__OO__,
	    b__OO__,
	    b__O___},
    [0x3c] {b____O_,
	    b___O__,
	    b__O___,
	    b_O____,
	    b__O___,
	    b___O__,
	    b____O_,
	    b______},
    [0x3d] {b______,
	    b______,
	    b_OOOOO,
	    b______,
	    b______,
	    b_OOOOO,
	    b______,
	    b______},
    [0x3e] {b__O___,
	    b___O__,
	    b____O_,
	    b_____O,
	    b____O_,
	    b___O__,
	    b__O___,
	    b______},
    [0x3f] {b__OOO_,
	    b_O___O,
	    b_____O,
	    b___OO_,
	    b___O__,
	    b______,
	    b___O__,
	    b______},
    [0x40] {b__OOO_,
	    b_O___O,
	    b_O_OOO,
	    b_O_O_O,
	    b_O_OOO,
	    b_O____,
	    b__OOO_,
	    b______},
    [0x41] {b__OOO_,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b_OOOOO,
	    b_O___O,
	    b_O___O,
	    b______},
    [0x42] {b_OOOO_,
	    b_O___O,
	    b_O___O,
	    b_OOOO_,
	    b_O___O,
	    b_O___O,
	    b_OOOO_,
	    b______},
    [0x43] {b__OOO_,
	    b_O___O,
	    b_O____,
	    b_O____,
	    b_O____,
	    b_O___O,
	    b__OOO_,
	    b______},
    [0x44] {b_OOOO_,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b_OOOO_,
	    b______},
    [0x45] {b_OOOOO,
	    b_O____,
	    b_O____,
	    b_OOOO_,
	    b_O____,
	    b_O____,
	    b_OOOOO,
	    b______},
    [0x46] {b_OOOOO,
	    b_O____,
	    b_O____,
	    b_OOOO_,
	    b_O____,
	    b_O____,
	    b_O____,
	    b______},
    [0x47] {b__OOO_,
	    b_O___O,
	    b_O____,
	    b_O_OOO,
	    b_O___O,
	    b_O___O,
	    b__OOOO,
	    b______},
    [0x48] {b_O___O,
	    b_O___O,
	    b_O___O,
	    b_OOOOO,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b______},
    [0x49] {b__OOO_,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b__OOO_,
	    b______},
    [0x4a] {b_____O,
	    b_____O,
	    b_____O,
	    b_____O,
	    b_O___O,
	    b_O___O,
	    b__OOO_,
	    b______},
    [0x4b] {b_O___O,
	    b_O__O_,
	    b_O_O__,
	    b_OO___,
	    b_O_O__,
	    b_O__O_,
	    b_O___O,
	    b______},
    [0x4c] {b_O____,
	    b_O____,
	    b_O____,
	    b_O____,
	    b_O____,
	    b_O____,
	    b_OOOOO,
	    b______},
    [0x4d] {b_O___O,
	    b_OO_OO,
	    b_O_O_O,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b______},
    [0x4e] {b_O___O,
	    b_OO__O,
	    b_O_O_O,
	    b_O__OO,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b______},
    [0x4f] {b__OOO_,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b__OOO_,
	    b______},
    [0x50] {b_OOOO_,
	    b_O___O,
	    b_O___O,
	    b_OOOO_,
	    b_O____,
	    b_O____,
	    b_O____,
	    b______},
    [0x51] {b__OOO_,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b_O_O_O,
	    b_O__O_,
	    b__OO_O,
	    b______},
    [0x52] {b_OOOO_,
	    b_O___O,
	    b_O___O,
	    b_OOOO_,
	    b_O__O_,
	    b_O___O,
	    b_O___O,
	    b______},
    [0x53] {b__OOO_,
	    b_O___O,
	    b_O____,
	    b__OOO_,
	    b_____O,
	    b_O___O,
	    b__OOO_,
	    b______},
    [0x54] {b_OOOOO,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b______},
    [0x55] {b_O___O,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b__OOO_,
	    b______},
    [0x56] {b_O___O,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b__O_O_,
	    b___O__,
	    b______},
    [0x57] {b_O___O,
	    b_O___O,
	    b_O_O_O,
	    b_O_O_O,
	    b_O_O_O,
	    b_O_O_O,
	    b__O_O_,
	    b______},
    [0x58] {b_O___O,
	    b_O___O,
	    b__O_O_,
	    b___O__,
	    b__O_O_,
	    b_O___O,
	    b_O___O,
	    b______},
    [0x59] {b_O___O,
	    b_O___O,
	    b_O___O,
	    b__O_O_,
	    b___O__,
	    b___O__,
	    b___O__,
	    b______},
    [0x5a] {b_OOOO_,
	    b____O_,
	    b___O__,
	    b__O___,
	    b_O____,
	    b_O____,
	    b_OOOO_,
	    b______},
    [0x5b] {b__OOO_,
	    b__O___,
	    b__O___,
	    b__O___,
	    b__O___,
	    b__O___,
	    b__OOO_,
	    b______},
    [0x5c] {b______,
	    b_O____,
	    b__O___,
	    b___O__,
	    b____O_,
	    b_____O,
	    b______,
	    b______},
    [0x5d] {b__OOO_,
	    b____O_,
	    b____O_,
	    b____O_,
	    b____O_,
	    b____O_,
	    b__OOO_,
	    b______},
    [0x5e] {b___O__,
	    b__O_O_,
	    b_O___O,
	    b______,
	    b______,
	    b______,
	    b______,
	    b______},
    [0x5f] {b______,
	    b______,
	    b______,
	    b______,
	    b______,
	    b______,
	    b______,
	    bOOOOOO},
    [0x60] {b__OO__,
	    b__OO__,
	    b___O__,
	    b______,
	    b______,
	    b______,
	    b______,
	    b______},
    [0x61] {b______,
	    b______,
	    b__OOO_,
	    b_____O,
	    b__OOOO,
	    b_O___O,
	    b__OOOO,
	    b______},
    [0x62] {b_O____,
	    b_O____,
	    b_OOOO_,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b_OOOO_,
	    b______},
    [0x63] {b______,
	    b______,
	    b__OOO_,
	    b_O___O,
	    b_O____,
	    b_O___O,
	    b__OOO_,
	    b______},
    [0x64] {b_____O,
	    b_____O,
	    b__OOOO,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b__OOOO,
	    b______},
    [0x65] {b______,
	    b______,
	    b__OOO_,
	    b_O___O,
	    b_OOOO_,
	    b_O____,
	    b__OOO_,
	    b______},
    [0x66] {b___OO_,
	    b__O___,
	    b__O___,
	    b_OOOO_,
	    b__O___,
	    b__O___,
	    b__O___,
	    b______},
    [0x67] {b______,
	    b______,
	    b__OOOO,
	    b_O___O,
	    b_O___O,
	    b__OOOO,
	    b_____O,
	    b__OOO_},
    [0x68] {b_O____,
	    b_O____,
	    b_OOO__,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b______},
    [0x69] {b___O__,
	    b______,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___OO_,
	    b______},
    [0x6a] {b____O_,
	    b______,
	    b___OO_,
	    b____O_,
	    b____O_,
	    b____O_,
	    b_O__O_,
	    b__OO__},
    [0x6b] {b_O____,
	    b_O____,
	    b_O__O_,
	    b_O_O__,
	    b_OO___,
	    b_O_O__,
	    b_O__O_,
	    b______},
    [0x6c] {b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___OO_,
	    b______},
    [0x6d] {b______,
	    b______,
	    b_OO_O_,
	    b_O_O_O,
	    b_O_O_O,
	    b_O___O,
	    b_O___O,
	    b______},
    [0x6e] {b______,
	    b______,
	    b_OOO__,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b______},
    [0x6f] {b______,
	    b______,
	    b__OOO_,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b__OOO_,
	    b______},
    [0x70] {b______,
	    b______,
	    b_OOOO_,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b_OOOO_,
	    b_O____},
    [0x71] {b______,
	    b______,
	    b__OOOO,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b__OOOO,
	    b_____O},
    [0x72] {b______,
	    b______,
	    b_O_OO_,
	    b__O__O,
	    b__O___,
	    b__O___,
	    b_OOO__,
	    b______},
    [0x73] {b______,
	    b______,
	    b__OOO_,
	    b_O____,
	    b__OOO_,
	    b_____O,
	    b__OOO_,
	    b______},
    [0x74] {b______,
	    b__O___,
	    b_OOOO_,
	    b__O___,
	    b__O___,
	    b__O_O_,
	    b___O__,
	    b______},
    [0x75] {b______,
	    b______,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b_O_OO_,
	    b__O_O_,
	    b______},
    [0x76] {b______,
	    b______,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b__O_O_,
	    b___O__,
	    b______},
    [0x77] {b______,
	    b______,
	    b_O___O,
	    b_O___O,
	    b_O_O_O,
	    b_OOOOO,
	    b__O_O_,
	    b______},
    [0x78] {b______,
	    b______,
	    b_O__O_,
	    b_O__O_,
	    b__OO__,
	    b_O__O_,
	    b_O__O_,
	    b______},
    [0x79] {b______,
	    b______,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b__OOO_,
	    b___O__,
	    b_OO___},
    [0x7a] {b______,
	    b______,
	    b_OOOO_,
	    b____O_,
	    b__OO__,
	    b_O____,
	    b_OOOO_,
	    b______},
    [0x7b] {b___OO_,
	    b__O___,
	    b__O___,
	    b_OO___,
	    b__O___,
	    b__O___,
	    b___OO_,
	    b______},
    [0x7c] {b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__},
    [0x7d] {b__OO__,
	    b____O_,
	    b____O_,
	    b____OO,
	    b____O_,
	    b____O_,
	    b__OO__,
	    b______},
    [0x7e] {b__O_O_,
	    b_O_O__,
	    b______,
	    b______,
	    b______,
	    b______,
	    b______,
	    b______},
    [0x7f] {b___O__,
	    b__OOO_,
	    b_OO_OO,
	    b_O___O,
	    b_O___O,
	    b_OOOOO,
	    b______,
	    b______},
    [0x80] {b__OOO_,
	    b_O___O,
	    b_O____,
	    b_O____,
	    b_O___O,
	    b__OOO_,
	    b___O__,
	    b__OO__},
    [0x81] {b_O__O_,
	    b______,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b_O_OO_,
	    b__O_O_,
	    b______},
    [0x82] {b____OO,
	    b______,
	    b__OOO_,
	    b_O___O,
	    b_OOOO_,
	    b_O____,
	    b__OOO_,
	    b______},
    [0x83] {b__OOO_,
	    b______,
	    b__OOO_,
	    b_____O,
	    b__OOOO,
	    b_O___O,
	    b__OOOO,
	    b______},
    [0x84] {b__O_O_,
	    b______,
	    b__OOO_,
	    b_____O,
	    b__OOOO,
	    b_O___O,
	    b__OOOO,
	    b______},
    [0x85] {b__OO__,
	    b______,
	    b__OOO_,
	    b_____O,
	    b__OOOO,
	    b_O___O,
	    b__OOOO,
	    b______},
    [0x86] {b__OOO_,
	    b__O_O_,
	    b__OOO_,
	    b_____O,
	    b__OOOO,
	    b_O___O,
	    b__OOOO,
	    b______},
    [0x87] {b______,
	    b__OOO_,
	    b_O___O,
	    b_O____,
	    b_O___O,
	    b__OOO_,
	    b___O__,
	    b__OO__},
    [0x88] {b__OOO_,
	    b______,
	    b__OOO_,
	    b_O___O,
	    b_OOOO_,
	    b_O____,
	    b__OOO_,
	    b______},
    [0x89] {b__O_O_,
	    b______,
	    b__OOO_,
	    b_O___O,
	    b_OOOO_,
	    b_O____,
	    b__OOO_,
	    b______},
    [0x8a] {b__OO__,
	    b______,
	    b__OOO_,
	    b_O___O,
	    b_OOOO_,
	    b_O____,
	    b__OOO_,
	    b______},
    [0x8b] {b__O_O_,
	    b______,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___OO_,
	    b______},
    [0x8c] {b___O__,
	    b__O_O_,
	    b______,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___OO_,
	    b______},
    [0x8d] {b__O___,
	    b______,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___OO_,
	    b______},
    [0x8e] {b__O_O_,
	    b______,
	    b___O__,
	    b__O_O_,
	    b_O___O,
	    b_OOOOO,
	    b_O___O,
	    b______},
    [0x8f] {b__OOO_,
	    b__O_O_,
	    b__OOO_,
	    b_OO_OO,
	    b_O___O,
	    b_OOOOO,
	    b_O___O,
	    b______},
    [0x90] {b____OO,
	    b______,
	    b_OOOOO,
	    b_O____,
	    b_OOOO_,
	    b_O____,
	    b_OOOOO,
	    b______},
    [0x91] {b______,
	    b______,
	    b_OOOO_,
	    b___O_O,
	    b_OOOOO,
	    b_O_O__,
	    b__OOOO,
	    b______},
    [0x92] {b__OOOO,
	    b_O_O__,
	    b_O_O__,
	    b_OOOOO,
	    b_O_O__,
	    b_O_O__,
	    b_O_OOO,
	    b______},
    [0x93] {b__OOO_,
	    b______,
	    b__OO__,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b__OO__,
	    b______},
    [0x94] {b__O_O_,
	    b______,
	    b__OO__,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b__OO__,
	    b______},
    [0x95] {b_OO___,
	    b______,
	    b__OO__,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b__OO__,
	    b______},
    [0x96] {b__OOO_,
	    b______,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b_O_OO_,
	    b__O_O_,
	    b______},
    [0x97] {b_OO___,
	    b______,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b_O_OO_,
	    b__O_O_,
	    b______},
    [0x98] {b__O_O_,
	    b______,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b__OOO_,
	    b___O__,
	    b_OO___},
    [0x99] {b_O__O_,
	    b__OO__,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b__OO__,
	    b______},
    [0x9a] {b__O_O_,
	    b______,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b__OO__,
	    b______},
    [0x9b] {b______,
	    b___O__,
	    b__OOO_,
	    b_O____,
	    b_O____,
	    b__OOO_,
	    b___O__,
	    b______},
    [0x9c] {b___OO_,
	    b__O__O,
	    b__O___,
	    b_OOOO_,
	    b__O___,
	    b__O__O,
	    b_O_OOO,
	    b______},
    [0x9d] {b_O___O,
	    b__O_O_,
	    b___O__,
	    b_OOOOO,
	    b___O__,
	    b_OOOOO,
	    b___O__,
	    b______},
    [0x9e] {b_OO___,
	    b_O_O__,
	    b_O_O__,
	    b_OO_O_,
	    b_O_OOO,
	    b_O__O_,
	    b_O__O_,
	    b______},
    [0x9f] {b____O_,
	    b___O_O,
	    b___O__,
	    b__OOO_,
	    b___O__,
	    b___O__,
	    b_O_O__,
	    b__O___},
    [0xa0] {b___OO_,
	    b______,
	    b__OOO_,
	    b_____O,
	    b__OOOO,
	    b_O___O,
	    b__OOOO,
	    b______},
    [0xa1] {b___OO_,
	    b______,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___OO_,
	    b______},
    [0xa2] {b___OO_,
	    b______,
	    b__OO__,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b__OO__,
	    b______},
    [0xa3] {b___OO_,
	    b______,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b_O_OO_,
	    b__O_O_,
	    b______},
    [0xa4] {b__O_O_,
	    b_O_O__,
	    b______,
	    b_OOO__,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b______},
    [0xa5] {b__O_O_,
	    b_O_O__,
	    b______,
	    b_O__O_,
	    b_OO_O_,
	    b_O_OO_,
	    b_O__O_,
	    b______},
    [0xa6] {b__OOO_,
	    b_____O,
	    b__OOOO,
	    b_O___O,
	    b__OOOO,
	    b______,
	    b__OOOO,
	    b______},
    [0xa7] {b__OO__,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b__OO__,
	    b______,
	    b_OOOO_,
	    b______},
    [0xa8] {b___O__,
	    b______,
	    b___O__,
	    b__OO__,
	    b_O____,
	    b_O___O,
	    b__OOO_,
	    b______},
    [0xa9] {b______,
	    b______,
	    b_OOOOO,
	    b_O____,
	    b_O____,
	    b_O____,
	    b______,
	    b______},
    [0xaa] {b______,
	    b______,
	    bOOOOOO,
	    b_____O,
	    b_____O,
	    b______,
	    b______,
	    b______},
    [0xab] {b_O____,
	    b_O__O_,
	    b_O_O__,
	    b__OOO_,
	    b_O___O,
	    b____O_,
	    b___OOO,
	    b______},
    [0xac] {b_O____,
	    b_O__O_,
	    b_O_O__,
	    b__O_OO,
	    b_O_O_O,
	    b___OOO,
	    b_____O,
	    b______},
    [0xad] {b___O__,
	    b______,
	    b___O__,
	    b___O__,
	    b__OOO_,
	    b__OOO_,
	    b___O__,
	    b______},
    [0xae] {b______,
	    b______,
	    b__O__O,
	    b_O__O_,
	    b__O__O,
	    b______,
	    b______,
	    b______},
    [0xaf] {b______,
	    b______,
	    b_O__O_,
	    b__O__O,
	    b_O__O_,
	    b______,
	    b______,
	    b______},
    [0xb0] {b_O_O_O,
	    b______,
	    bO_O_O_,
	    b______,
	    b_O_O_O,
	    b______,
	    bO_O_O_,
	    b______},
    [0xb1] {b_O_O_O,
	    bO_O_O_,
	    b_O_O_O,
	    bO_O_O_,
	    b_O_O_O,
	    bO_O_O_,
	    b_O_O_O,
	    bO_O_O_},
    [0xb2] {bO_O_O_,
	    bOOOOOO,
	    b_O_O_O,
	    bOOOOOO,
	    bO_O_O_,
	    bOOOOOO,
	    b_O_O_O,
	    bOOOOOO},
    [0xb3] {b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__},
    [0xb4] {b___O__,
	    b___O__,
	    b___O__,
	    bOOOO__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__},
    [0xb5] {b______,
	    b______,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b_OOO__,
	    b_O____,
	    b_O____},
    [0xb6] {b_O_O__,
	    b_O_O__,
	    b_O_O__,
	    bOO_O__,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__},
    [0xb7] {b______,
	    b______,
	    b______,
	    bOOOO__,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__},
    [0xb8] {b______,
	    bOOOO__,
	    b___O__,
	    bOOOO__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__},
    [0xb9] {b_O_O__,
	    bOO_O__,
	    b___O__,
	    bOO_O__,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__},
    [0xba] {b_O_O__,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__},
    [0xbb] {b______,
	    bOOOO__,
	    b___O__,
	    bOO_O__,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__},
    [0xbc] {b_O_O__,
	    bOO_O__,
	    b___O__,
	    bOOOO__,
	    b______,
	    b______,
	    b______,
	    b______},
    [0xbd] {b_O_O__,
	    b_O_O__,
	    b_O_O__,
	    bOOOO__,
	    b______,
	    b______,
	    b______,
	    b______},
    [0xbe] {b___O__,
	    bOOOO__,
	    b___O__,
	    bOOOO__,
	    b______,
	    b______,
	    b______,
	    b______},
    [0xbf] {b______,
	    b______,
	    b______,
	    bOOOO__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__},
    [0xc0] {b___O__,
	    b___O__,
	    b___O__,
	    b___OOO,
	    b______,
	    b______,
	    b______,
	    b______},
    [0xc1] {b___O__,
	    b___O__,
	    b___O__,
	    bOOOOOO,
	    b______,
	    b______,
	    b______,
	    b______},
    [0xc2] {b______,
	    b______,
	    b______,
	    bOOOOOO,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__},
    [0xc3] {b___O__,
	    b___O__,
	    b___O__,
	    b___OOO,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__},
    [0xc4] {b______,
	    b______,
	    b______,
	    bOOOOOO,
	    b______,
	    b______,
	    b______,
	    b______},
    [0xc5] {b___O__,
	    b___O__,
	    b___O__,
	    bOOOOOO,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__},
    [0xc6] {b___O__,
	    b___OOO,
	    b___O__,
	    b___OOO,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__},
    [0xc7] {b_O_O__,
	    b_O_O__,
	    b_O_O__,
	    b_O_OOO,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__},
    [0xc8] {b_O_O__,
	    b_O_OOO,
	    b_O____,
	    b_OOOOO,
	    b______,
	    b______,
	    b______,
	    b______},
    [0xc9] {b______,
	    b_OOOOO,
	    b_O____,
	    b_O_OOO,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__},
    [0xca] {b_O_O__,
	    bOO_OOO,
	    b______,
	    bOOOOOO,
	    b______,
	    b______,
	    b______,
	    b______},
    [0xcb] {b______,
	    bOOOOOO,
	    b______,
	    bOO_OOO,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__},
    [0xcc] {b_O_O__,
	    b_O_OOO,
	    b_O____,
	    b_O_OOO,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__},
    [0xcd] {b______,
	    bOOOOOO,
	    b______,
	    bOOOOOO,
	    b______,
	    b______,
	    b______,
	    b______},
    [0xce] {b_O_O__,
	    bOO_OOO,
	    b______,
	    bOO_OOO,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__},
    [0xcf] {b___O__,
	    bOOOOOO,
	    b______,
	    bOOOOOO,
	    b______,
	    b______,
	    b______,
	    b______},
    [0xd0] {b_O_O__,
	    b_O_O__,
	    b_O_O__,
	    bOOOOOO,
	    b______,
	    b______,
	    b______,
	    b______},
    [0xd1] {b______,
	    bOOOOOO,
	    b______,
	    bOOOOOO,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__},
    [0xd2] {b______,
	    b______,
	    b______,
	    bOOOOOO,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__,
	    b_O_O__},
    [0xd3] {b_O_O__,
	    b_O_O__,
	    b_O_O__,
	    b_OOOOO,
	    b______,
	    b______,
	    b______,
	    b______},
    [0xd4] {b______,
	    b______,
	    b______,
	    b______,
	    b______,
	    b______,
	    b______,
	    bOOOOOO},
    [0xd5] {b______,
	    b______,
	    b______,
	    b______,
	    b______,
	    b______,
	    bOOOOOO,
	    bOOOOOO},
    [0xd6] {b______,
	    b______,
	    b______,
	    b______,
	    b______,
	    bOOOOOO,
	    bOOOOOO,
	    bOOOOOO},
    [0xd7] {b______,
	    b______,
	    b______,
	    b______,
	    bOOOOOO,
	    bOOOOOO,
	    bOOOOOO,
	    bOOOOOO},
    [0xd8] {b______,
	    b______,
	    b______,
	    bOOOOOO,
	    bOOOOOO,
	    bOOOOOO,
	    bOOOOOO,
	    bOOOOOO},
    [0xd9] {b______,
	    b______,
	    bOOOOOO,
	    bOOOOOO,
	    bOOOOOO,
	    bOOOOOO,
	    bOOOOOO,
	    bOOOOOO},
    [0xda] {b______,
	    bOOOOOO,
	    bOOOOOO,
	    bOOOOOO,
	    bOOOOOO,
	    bOOOOOO,
	    bOOOOOO,
	    bOOOOOO},
    [0xdb] {bOOOOOO,
	    bOOOOOO,
	    bOOOOOO,
	    bOOOOOO,
	    bOOOOOO,
	    bOOOOOO,
	    bOOOOOO,
	    bOOOOOO},
    [0xdc] {bO_____,
	    bO_____,
	    bO_____,
	    bO_____,
	    bO_____,
	    bO_____,
	    bO_____,
	    bO_____},
    [0xdd] {bOO____,
	    bOO____,
	    bOO____,
	    bOO____,
	    bOO____,
	    bOO____,
	    bOO____,
	    bOO____},
    [0xde] {bOOO___,
	    bOOO___,
	    bOOO___,
	    bOOO___,
	    bOOO___,
	    bOOO___,
	    bOOO___,
	    bOOO___},
    [0xdf] {bOOOO__,
	    bOOOO__,
	    bOOOO__,
	    bOOOO__,
	    bOOOO__,
	    bOOOO__,
	    bOOOO__,
	    bOOOO__},
    [0xe0] {bOOOOO_,
	    bOOOOO_,
	    bOOOOO_,
	    bOOOOO_,
	    bOOOOO_,
	    bOOOOO_,
	    bOOOOO_,
	    bOOOOO_},
    [0xe1] {b______,
	    b_OOO__,
	    b_O__O_,
	    b_OOO__,
	    b_O__O_,
	    b_O__O_,
	    b_OOO__,
	    b_O____},
    [0xe2] {b_OOOO_,
	    b_O__O_,
	    b_O____,
	    b_O____,
	    b_O____,
	    b_O____,
	    b_O____,
	    b______},
    [0xe3] {b______,
	    b_OOOOO,
	    b__O_O_,
	    b__O_O_,
	    b__O_O_,
	    b__O_O_,
	    b__O_O_,
	    b______},
    [0xe4] {b__O_O_,
	    b______,
	    b__OOO_,
	    b_____O,
	    b__OOOO,
	    b_O___O,
	    b__OOOO,
	    b______},
    [0xe5] {b______,
	    b______,
	    b__OOOO,
	    b_O__O_,
	    b_O__O_,
	    b__OO__,
	    b______,
	    b______},
    [0xe6] {b______,
	    b______,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b_OOO__,
	    b_O____,
	    b_O____},
    [0xe7] {b______,
	    b______,
	    b__O_O_,
	    b_O_O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b______},
    [0xe8] {b__OOO_,
	    b___O__,
	    b__OOO_,
	    b_O___O,
	    b__OOO_,
	    b___O__,
	    b__OOO_,
	    b______},
    [0xe9] {b__OO__,
	    b_O__O_,
	    b_O__O_,
	    b_OOOO_,
	    b_O__O_,
	    b_O__O_,
	    b__OO__,
	    b______},
    [0xea] {b______,
	    b__OOO_,
	    b_O___O,
	    b_O___O,
	    b__O_O_,
	    b__O_O_,
	    b_OO_OO,
	    b______},
    [0xeb] {b__OO__,
	    b_O____,
	    b__O___,
	    b___O__,
	    b__OOO_,
	    b_O__O_,
	    b__OO__,
	    b______},
    [0xec] {b______,
	    b______,
	    b__O_O_,
	    b_O_O_O,
	    b_O_O_O,
	    b__O_O_,
	    b______,
	    b______},
    [0xed] {b______,
	    b___O__,
	    b__OOO_,
	    b_O_O_O,
	    b_O_O_O,
	    b__OOO_,
	    b___O__,
	    b______},
    [0xee] {b______,
	    b__OOO_,
	    b_O____,
	    b_OOOO_,
	    b_O____,
	    b__OOO_,
	    b______,
	    b______},
    [0xef] {b______,
	    b__OO__,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b______,
	    b______},
    [0xf0] {b______,
	    b_OOOO_,
	    b______,
	    b_OOOO_,
	    b______,
	    b_OOOO_,
	    b______,
	    b______},
    [0xf1] {b______,
	    b___O__,
	    b__OOO_,
	    b___O__,
	    b______,
	    b__OOO_,
	    b______,
	    b______},
    [0xf2] {b_O____,
	    b__OO__,
	    b____O_,
	    b__OO__,
	    b_O____,
	    b______,
	    b_OOOO_,
	    b______},
    [0xf3] {b______,
	    b______,
	    bOOOOOO,
	    bOOO___,
	    bO__OO_,
	    bO____O,
	    bO_____,
	    bOOOOOO},
    [0xf4] {b______,
	    b______,
	    bOOOOOO,
	    b___OOO,
	    b_OO__O,
	    bO____O,
	    b_____O,
	    bOOOOOO},
    [0xf5] {b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b___O__,
	    b_O_O__,
	    b__O___,
	    b______},
    [0xf6] {b__O_O_,
	    b______,
	    b__OOO_,
	    b_O___O,
	    b_O___O,
	    b_O___O,
	    b__OOO_,
	    b______},
    [0xf7] {bOOOOO_,
	    bOOOOO_,
	    bOOOOO_,
	    bOOOOO_,
	    bOOOOO_,
	    bOOOOO_,
	    bOOOOO_,
	    bOOOOO_},
    [0xf8] {bOOOO__,
	    bOOOO__,
	    bOOOO__,
	    bOOOO__,
	    bOOOO__,
	    bOOOO__,
	    bOOOO__,
	    bOOOO__},
    [0xf9] {bOOO___,
	    bOOO___,
	    bOOO___,
	    bOOO___,
	    bOOO___,
	    bOOO___,
	    bOOO___,
	    bOOO___},
    [0xfa] {bOO____,
	    bOO____,
	    bOO____,
	    bOO____,
	    bOO____,
	    bOO____,
	    bOO____,
	    bOO____},
    [0xfb] {bO_____,
	    bO_____,
	    bO_____,
	    bO_____,
	    bO_____,
	    bO_____,
	    bO_____,
	    bO_____},
    [0xfc] {b__O_O_,
	    b______,
	    b_O__O_,
	    b_O__O_,
	    b_O__O_,
	    b_O_OO_,
	    b__O_O_,
	    b______},
    [0xfd] {b_OO___,
	    b___O__,
	    b__O___,
	    b_OOO__,
	    b______,
	    b______,
	    b______,
	    b______},
    [0xfe] {b______,
	    b______,
	    b______,
	    b_OOOO_,
	    bOO__O_,
	    bOO__OO,
	    bOOOOO_,
	    b__OOOO},
    [0xff] {b_O__O_,
	    bOOOOOO,
	    b_O__O_,
	    b_O__O_,
	    bOOOOOO,
	    b_O__O_,
	    b______,
	    b______}
};
