.TH lcdexec 1 "2-aug-02" "lcdexec"
.SH NAME
lcdexec - allows user to execute commands from LCDproc server (LCDd(8))
.SH SYNOPSIS
.B lcdexec
.RB [\| \-c
.IR filename \|]
.RB [\| \-a
.IR address \|]
.RB [\| \-p
.IR port \|]
.RB [\| \-f
.IR bool \|]
.RB [\| \-r
.IR level \|]
.RB [\| \-s
.IR bool \|]

.SH DESCRIPTION
lcdexec connects to LCDd (the LCDproc server) and adds a submenu to the LCDd main menu. You can access the menu by pressing the menu key configured for LCDd.
.SH OPTIONS
.I lcdexec
understands the following options, with corresponding configfile settings between {} brackets:
.TP 8
.B \-c \fIfilename\fP
Set the name of the config file to read, /etc/LCDclients.conf by default
.TP 8
.B \-a \fIaddress\fP
Set the address of the host which LCDd is running on, localhost by default
{Address=\fIaddress\fP}
.TP 8
.B \-p \fIport\fP
Set the port which LCDd is accepting connections on, 13666 by default
{Port=\fIport\fP}
.TP 8
.B \-f \fIbool\fP
Run in foreground (1, default) or in background (0)
{Foreground=\fIbool\fP}
.TP 8
.B \-r \fIlevel\fP
Sets the reporting level, 0 (only critical errors) to 5 (debug messages), default is 2 (errors and warnings only)
{ReportLevel=\fIlevel\fP}
.TP 8
.B \-s \fIbool\fP
Report to syslog (1) or to stdout (0, default)
{ReportToSyslog=\fIbool\fP}
.PP
The executable commands can only be specified in the config file:
.TP 8
MenuCommand="\fItext\fB, \fIcommand\fB"
Adds a menuentry with the given visible text, which starts the given command when the user selects the entry.
.TP 8
SubMenu="\fItext\fB, \fImenuid\fB"
Adds a menuentry for a submenu with the given visible text.
.TP 8
\fImenuid\fP_MenuCommand="\fItext\fB, \fIcommand\fB"
Same as MenuCommand, but adds it to the given submenu.
.TP 8
\fImenuid\fP_SubMenu="\fItext\fB, \fImenuid\fB"
Same as SubMenu, but adds it to the given submenu. This way you can create multi-level menus.
.PP
All configfile settings should be put in the [lcdexec] section. You can use a quote in your text by escaping it with a backslash: \\".

.SH FILES
.TP
.B LCDclients.conf
This file should have a "ini-file"-like format, with sections that are preceded by a [section] header and lines that consist of key=value pairs. Strings with characters other than [a-za-Z0-9_] should be quoted with double quotes. If you want a quote or a backslash in the string, escape it by preceding it by a backslash.
.TP
The contents of the [lcdexec] section of this file should be as descriped in the options section.

.SH EXAMPLES
In the configfile:
.PP
.DS
.ft CW
.nf
[lcdexec]
MenuCommand="Eject CD-ROM, umount /cdrom; cdeject"
SubMenu="Shutdown menu, sd"
sd_MenuCommand="Shutdown in 5 minutes, shutdown -h +5"
sd_MenuCommand="Reboot in 5 minutes, shutdown -r +5"
sd_MenuCommand="Cancel shutdown/reboot, shutdown -c"
sd_MenuCommand="Shutdown now, shutdown -h now"
sd_MenuCommand="Reboot now, shutdown -r now"
.ft R
.fi
.DE

.PP
Start lcdexec with:
lcdexec -c /usr/local/etc/LCDclients.conf

.PP
This will allow you to eject the CD-ROM by opening the LCDd menu, selecting "lcdexec" and selecting "Eject CD-ROM". Further it allows you to do various shutdowns, among others the "Shutdown in 5 minutes" by opening the LCDd menu, selecting "lcdexec", selecting "Shutdown" and selecting "Shutdown in 5 minutes".

.Sh SEE ALSO
.Xr LCDd 8
.SH AUTHOR
lcdexec is writen by Joris Robijn. It is part of the LCDproc package.

The newest version of LCDproc should be available from here:

		http://lcdproc.omnipotents.net/

.SH LEGAL STUFF
LCDproc is released as "WorksForMe-Ware".  In other words, it is free, kinda neat, and we don't guarantee that it will do anything in particular on any machine except the ones it was developed on.
.PP
It is technically released under the GNU GPL license (you should have received the file, "COPYING", with LCDproc) (also, look on http://www.fsf.org/ for more information), so you can distribute and use it for free -- but you must make the source code freely available to anyone who wants it.
.PP
For any sort of real legal information, read the GNU GPL (GNU General Public License).  It's worth reading.
