.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH FORTUNE.PL 1 "December  9, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH NAME
fortune.pl \- client for LCDd, the lcdproc server
.SH SYNOPSIS
.B fortune.pl
.SH DESCRIPTION
.B fortune.pl
is a small example client for LCDd, the lcdproc server. For more
information please see
.BR lcdproc (1)
and
.BR LCDd (8),
and http://lcdproc.omnipotent.net/. Or better yet, read the source!
.PP
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
.SH SEE ALSO
.BR lcdproc (1),
.BR LCDd (8).
.br
.SH AUTHOR
This manual page was written by Jonathan Oxer <jon@debian.org>,
for the Debian project (but may be used by others).
